### ISSUE TITLE
Cannot lift recompiled example binaries

### ISSUE THREAD

**Issue by fan1x** [trailofbits/binrec-tob#78]
I'm trying to use binrec. I was able to compile and run the examples correctly. However, when I try to recompile the example binaries from sources (or just use my own hello world binaries), binrec always crashes. 

To compile my binaries, I connect to the S2E VM image (`s2e/images/debian-9.2.1-i386/image.raw.s2e`), compile the binaries there and then I let the binrec analyze those exact binaries. (Ofc, I'm using a copy of the image not to corrupt it). AFAIK, there should be no problem with missing dependencies or anything since I'm using the exact same VM as binrec. 

### Error
```
15:54:35 INFO binrec.merge: linking prepared bitcode: /tmp/binrec-tob/s2e/projects/myhello/s2e-out-2/captured-link-ready.bc
pipenv run python -m binrec.lift  "myhello" 
Loading .env environment variables…
15:54:36 INFO binrec.lift: lifting project myhello
Traceback (most recent call last):
  File "/tmp/binrec-tob/binrec/lift.py", line 380, in _lift_bitcode
    binrec_lift.lift(
_binrec_lift.LiftError: [recover_functions] Failed to located main via entrypoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/binrec-tob/binrec/lift.py", line 663, in <module>
    main()
  File "/tmp/binrec-tob/binrec/lift.py", line 658, in main
    lift_trace(args.project_name, opt_level, args.harden)
  File "/tmp/binrec-tob/binrec/lift.py", line 596, in lift_trace
    _lift_bitcode(merged_trace_dir)
  File "/tmp/binrec-tob/binrec/lift.py", line 387, in _lift_bitcode
    raise convert_lib_error(
binrec.errors.BinRecLiftingError: failed to perform initial lifting of LLVM bitcode: myhello: [recover_functions] Failed to located main via entrypoint
error: Recipe `lift-trace` failed on line 239 with exit code 1
error: Recipe `recover` failed on line 244 with exit code 1
```

### Questions
* Do you know what could be the problem and how to fix it? 
* What compiler+flags and environment were used to produce the test binaries?
* Do you potentially have time to fix it, or you no longer work in binrec? (I don't see any recent activity here). 
* Orthogonal question: You mention `BinRec has very limited support for C++ programs.`.  What exactly does it mean?  What is not implemented? 

### Potential issue - bug? 
The code related to the error contains a comment saying.
```c++
    // NOTE (hbrodin):
    // Previous implementation/versions of BinRec and S2E didn't instrument starting at the
    // entrypoint in the updated S2E we do. Because of this the previous method for identifying
    // "main" doesn't any more. Previously they could rely on multiple "entry-points", first being
    // __libc_csu_init and then, the second time, main. Our updated approach looks like this: First
    // block: _start, it has one call to get the eip, on return from that we enter a block with a
    // call to __libc_start_main, wich later will call main the address of main is passed in
    // register eax. Unfortunately, we don't have any symbols at this point. The ieda is instead to
    // walk the successors to find the third block (having the call to __libc_start_main)
    // and locate the last store to eax, this "should" be the address of main.
    uint32_t locate_main_addr(Function *entrypoint, Module &m)
```

### Potential issue - Binary difference? 
I noticed that there is still some difference between the binaries, e.g., when I try to see the dynamic libraries with `objdump -T`. Not sure that could be the problem? (the different GLIBC?) 
```asm
; my binary
DYNAMIC SYMBOL TABLE:
00000000  w   D  *UND*  00000000              _ITM_deregisterTMCloneTable
00000000  w   DF *UND*  00000000  GLIBC_2.1.3 __cxa_finalize
00000000      DF *UND*  00000000  GLIBC_2.0   puts
00000000  w   D  *UND*  00000000              __gmon_start__
00000000      DF *UND*  00000000  GLIBC_2.0   __libc_start_main
00000000  w   D  *UND*  00000000              _Jv_RegisterClasses
00000000  w   D  *UND*  00000000              _ITM_registerTMCloneTable
000005ed g    DF .text  0000003c  Base        main
000006ac g    DO .rodata        00000004  Base        _IO_stdin_used

; test binary
DYNAMIC SYMBOL TABLE:
00000000      DF *UND*  00000000  GLIBC_2.0   puts
00000000  w   D  *UND*  00000000              __gmon_start__
00000000      DF *UND*  00000000  GLIBC_2.0   __libc_start_main
0804a004 g    DO .rodata        00000004  Base        _IO_stdin_used
```

Thanks a lot for your help!

**Comment by pzfl** [comment]
I am not familiar with this version of BinRec. It seems you compiled your binary as position independent executable. I have not looked at the code, but I suspect this implementation does not rebase addresses collected at runtime. In this case, the entry point detection should not be able to correlate them with the corresponding sections of the input binary. Try passing `-no-pie` to the compiler when linking your test programs.

**Comment by fan1x** [comment]
Indeed, I just figured today as well. Compiling with `-no-pie` works like a charm. Thanks a lot for the help 🙏
